# Generated by Django 5.2.6 on 2026-03-18 13:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('icon_url', models.URLField(blank=True, default='', max_length=500)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Equipment Category',
                'verbose_name_plural': 'Equipment Categories',
                'ordering': ['display_order', 'category_name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.CharField(max_length=255)),
                ('equipment_code', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('total_quantity', models.PositiveIntegerField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('unit_price_per_day', models.DecimalField(decimal_places=2, max_digits=12)),
                ('condition', models.CharField(choices=[('NEW', 'New'), ('GOOD', 'Good'), ('FAIR', 'Fair'), ('NEEDS_MAINTENANCE', 'Needs Maintenance')], default='GOOD', max_length=20)),
                ('storage_location', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipments', to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipments',
                'ordering': ['category__display_order', 'equipment_name'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='equipment.equipment')),
            ],
            options={
                'verbose_name': 'Equipment Image',
                'verbose_name_plural': 'Equipment Images',
                'ordering': ['display_order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PricingRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_days', models.PositiveIntegerField()),
                ('max_days', models.PositiveIntegerField()),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('effective_from', models.DateField()),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='equipment.equipmentcategory')),
            ],
            options={
                'verbose_name': 'Pricing Rule',
                'verbose_name_plural': 'Pricing Rules',
                'ordering': ['category', 'min_days'],
            },
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__lte', models.F('total_quantity'))), name='available_qty_lte_total_qty'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_per_day__gt', 0)), name='unit_price_gt_zero'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('max_days__gt', models.F('min_days'))), name='max_days_gt_min_days'),
        ),
        migrations.AddConstraint(
            model_name='pricingrule',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0)), name='discount_percentage_gte_zero'),
        ),
    ]
