# Generated by Django 5.2.6 on 2026-04-12 20:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('zone_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('base_transport_fee', models.DecimalField(decimal_places=2, help_text='Flat delivery fee (KES) for this zone.', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Transport Zone',
                'verbose_name_plural': 'Transport Zones',
                'ordering': ['zone_name'],
            },
        ),
        migrations.AddField(
            model_name='equipment',
            name='acquisition_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original purchase price per unit.', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='acquisition_date',
            field=models.DateField(blank=True, help_text='Date the equipment was acquired.', null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='personnel_cost_per_day',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Extra daily cost for technician support (KES).', max_digits=10),
        ),
        migrations.AddField(
            model_name='equipment',
            name='personnel_description',
            field=models.CharField(blank=True, default='', help_text="Description of personnel requirement, e.g. 'Certified 3D printer technician'.", max_length=255),
        ),
        migrations.AddField(
            model_name='equipment',
            name='requires_personnel',
            field=models.BooleanField(default=False, help_text='Whether this equipment needs a technician during use.'),
        ),
    ]
