# Generated by Django 5.2.6 on 2026-05-03 16:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_transportzone_equipment_acquisition_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='is_consumable',
            field=models.BooleanField(default=False, help_text='Consumable items (reagents, paper) are single-use. No physical return expected.'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='overdue_penalty_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.50'), help_text='Multiplier on unit_price_per_day charged per overdue day (1.50 = 150% of daily rate).', max_digits=5),
        ),
    ]
