# Generated by Django 5.2.6 on 2026-05-13 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_is_consumable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='buffer_stock',
            field=models.PositiveIntegerField(default=0, help_text='Number of units held back as a reserve and never shown as bookable. Used to absorb overdue conflicts. Typically 10–15% of total_quantity.'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.CheckConstraint(condition=models.Q(('buffer_stock__lt', models.F('total_quantity'))), name='buffer_stock_lt_total_qty'),
        ),
    ]
