# Generated by Django 5.2.6 on 2026-05-13 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_equipment_buffer_stock_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='equipment',
            name='buffer_stock_lt_total_qty',
        ),
        migrations.RemoveField(
            model_name='equipment',
            name='buffer_stock',
        ),
    ]
