# Generated by Django 5.2.6 on 2026-03-18 20:37

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentIssuance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('issue_notes', models.TextField(blank=True, default='')),
                ('issue_photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='issuance', to='bookings.booking')),
                ('issued_by', models.ForeignKey(help_text='ADMIN who handed over the equipment.', on_delete=django.db.models.deletion.PROTECT, related_name='issued_equipments', to=settings.AUTH_USER_MODEL)),
                ('received_by', models.ForeignKey(help_text='SCHOOL user who collected.', on_delete=django.db.models.deletion.PROTECT, related_name='received_issuances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Issuance',
                'verbose_name_plural': 'Equipment Issuances',
                'ordering': ['-issued_at'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentReturn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('returned_at', models.DateTimeField(auto_now_add=True)),
                ('return_notes', models.TextField(blank=True, default='')),
                ('return_photo_url', models.URLField(blank=True, default='', max_length=500)),
                ('has_damage', models.BooleanField(default=False)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='equipment_return', to='bookings.booking')),
                ('received_by', models.ForeignKey(help_text='ADMIN who received the equipment back.', on_delete=django.db.models.deletion.PROTECT, related_name='received_returns', to=settings.AUTH_USER_MODEL)),
                ('returned_by', models.ForeignKey(help_text='SCHOOL user who returned the equipment.', on_delete=django.db.models.deletion.PROTECT, related_name='returned_equipments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Equipment Return',
                'verbose_name_plural': 'Equipment Returns',
                'ordering': ['-returned_at'],
            },
        ),
    ]
