# Generated by Django 5.2.6 on 2026-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuances', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipmentissuance',
            name='delivery_notes',
            field=models.TextField(blank=True, default='', help_text='Notes on late or failed delivery — reason, follow-up action, etc.'),
        ),
        migrations.AddField(
            model_name='equipmentissuance',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending Delivery'), ('ON_TIME', 'Delivered On Time'), ('LATE', 'Delivered Late'), ('FAILED', 'Delivery Failed')], default='PENDING', help_text='Outcome of the physical delivery/handover.', max_length=20),
        ),
    ]
