# Generated by Django 5.2.6 on 2026-03-18 20:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookings', '0001_initial'),
        ('issuances', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DamageReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity_damaged', models.PositiveIntegerField(default=1)),
                ('severity', models.CharField(choices=[('MINOR', 'Minor'), ('MODERATE', 'Moderate'), ('SEVERE', 'Severe')], default='MINOR', max_length=20)),
                ('description', models.TextField()),
                ('photo_urls', models.JSONField(blank=True, default=list)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('resolution_status', models.CharField(choices=[('PENDING', 'Pending Assessment'), ('CHARGED', 'Charged to School'), ('WAIVED', 'Waived/Forgiven'), ('RESOLVED', 'Resolved and Closed')], default='PENDING', max_length=20)),
                ('booking_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='bookings.bookingitem')),
                ('equipment_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damage_reports', to='issuances.equipmentreturn')),
                ('reported_by', models.ForeignKey(help_text='ADMIN who reported the damage.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Damage Report',
                'verbose_name_plural': 'Damage Reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
