# Generated by Django 5.2.6 on 2026-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('damages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='damagereport',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount the school has paid toward this damage.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Assessed repair/replacement cost.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='damagereport',
            name='resolution_status',
            field=models.CharField(choices=[('PENDING', 'Pending Assessment'), ('CHARGED', 'Charged to School'), ('PAID', 'Paid by School'), ('WAIVED', 'Waived/Forgiven'), ('RESOLVED', 'Resolved and Closed')], default='PENDING', max_length=20),
        ),
    ]
