# Generated by Django 5.2.6 on 2026-04-12 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_transportzone_equipment_acquisition_cost_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolprofile',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='liability_status',
            field=models.CharField(choices=[('CLEAR', 'Clear'), ('HAS_OUTSTANDING', 'Has Outstanding Liabilities')], default='CLEAR', help_text='Blocks new bookings if HAS_OUTSTANDING.', max_length=20),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='town',
            field=models.CharField(blank=True, default='', help_text='Town or locality of the school.', max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='transport_zone',
            field=models.ForeignKey(blank=True, help_text='The transport zone used to calculate delivery fees.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_profiles', to='equipment.transportzone'),
        ),
    ]
