# Generated by Django 5.2.6 on 2026-05-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_schoolprofile_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=12, null=True),
        ),
    ]
