# Generated by Django 5.2.6 on 2026-05-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_gps_fields_precision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='gps_latitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='gps_longitude',
            field=models.DecimalField(blank=True, decimal_places=16, max_digits=18, null=True),
        ),
    ]
