# Generated by Django 5.2.6 on 2026-05-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_schoolprofile_gps_latitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='terms_accepted',
            field=models.BooleanField(default=False, help_text='User has accepted the platform Terms and Conditions.'),
        ),
        migrations.AddField(
            model_name='user',
            name='terms_accepted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp at which the user accepted the Terms and Conditions.', null=True),
        ),
    ]
