# Generated by Django 5.2.6 on 2026-05-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_terms_accepted_user_terms_accepted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolprofile',
            name='registration_number',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, unique=True),
        ),
    ]
