# Generated by Django 5.2.6 on 2026-03-30 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CANCEL', 'Cancel'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('PAYMENT', 'Payment'), ('RESOLVE', 'Resolve')], max_length=20)),
                ('object_id', models.CharField(blank=True, help_text='Primary key (UUID) of the affected record.', max_length=50)),
                ('object_repr', models.CharField(blank=True, help_text='Human-readable string representation of the affected record at the time of the action.', max_length=200)),
                ('changes', models.JSONField(blank=True, help_text='Dict describing what changed. Keys are field names; values are [old, new] pairs.', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, help_text='User who performed the action. Null for system-triggered actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
