# Generated by Django 5.2.6 on 2026-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('CANCEL', 'Cancel'), ('APPROVE', 'Approve'), ('DISPATCH', 'Dispatch'), ('ISSUE', 'Issue'), ('RETURN', 'Return'), ('COMPLETE', 'Complete'), ('PAYMENT', 'Payment'), ('RESOLVE', 'Resolve')], max_length=20),
        ),
    ]
