# Generated by Django 5.2.6 on 2026-04-12 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_add_cart_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='requires_transport',
            field=models.BooleanField(default=False, help_text='Whether the school requested LabSynch delivery.'),
        ),
        migrations.AddField(
            model_name='booking',
            name='transport_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Delivery fee (KES), 0 if school handles own transport.', max_digits=10),
        ),
        migrations.AddField(
            model_name='bookingitem',
            name='personnel_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional technician cost for this line item.', max_digits=10),
        ),
        migrations.AddField(
            model_name='cart',
            name='requires_transport',
            field=models.BooleanField(default=False, help_text='Whether the school needs LabSynch delivery.'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('RESERVED', 'Reserved (Paid)'), ('DISPATCHED', 'Dispatched'), ('IN_USE', 'In Use'), ('RETURNED', 'Returned'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
