# Generated by Django 5.2.6 on 2026-05-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_requires_transport_booking_transport_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='overdue_penalty',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Penalty charged for returning equipment past the agreed return_date.', max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('RESERVED', 'Reserved (Paid)'), ('DISPATCHED', 'Dispatched'), ('IN_USE', 'In Use'), ('RETURNED', 'Returned'), ('COMPLETED', 'Completed'), ('OVERDUE', 'Overdue'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
