# Generated by Django 5.2.6 on 2026-05-03 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_booking_overdue_penalty_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='penalty_cleared',
            field=models.BooleanField(default=False, help_text='Set by admin once the school has settled the overdue penalty.'),
        ),
    ]
