# Generated by Django 5.2.6 on 2026-05-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_add_penalty_cleared'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='penalty_carried_forward',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Total outstanding overdue penalties from previous bookings rolled into this booking's total. Paid alongside the regular booking amount.", max_digits=12),
        ),
        migrations.AlterField(
            model_name='booking',
            name='penalty_cleared',
            field=models.BooleanField(default=False, help_text='True once the overdue penalty on this booking has been settled.'),
        ),
    ]
