# Generated by Django 5.2.6 on 2026-05-03 23:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification_type', models.CharField(choices=[('BOOKING_CREATED', 'Booking Created'), ('PAYMENT_RECEIVED', 'Payment Received'), ('EQUIPMENT_ISSUED', 'Equipment Issued'), ('EQUIPMENT_RETURNED', 'Equipment Returned'), ('EQUIPMENT_OVERDUE', 'Equipment Overdue'), ('BOOKING_CANCELLED', 'Booking Cancelled'), ('PENALTY_CLEARED', 'Penalty Cleared'), ('GENERAL', 'General')], default='GENERAL', max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('booking_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('payment_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('issuance_id', models.UUIDField(blank=True, db_index=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx')],
            },
        ),
    ]
